### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by granmoe** [PauloSeb/midiServer#1]
Hi, thanks for creating this project.

I get the following error when running it:

Segmentation fault (core dumped)

I applied change to the midi source code:

https://github.com/justinlatimer/node-midi/pull/32

But the error still occurs.

I'm running Node 0.10.24 on Ubuntu 12.04 LTS. I just put \* for version in my package.json dependencies and ran npm install with no errors.

**Comment by PauloSeb** [comment]
Hi, thanks for using this project!

I updated node.js to v0.10.24 and the required modules (midi 0.7.0) but I can't reproduce the error on OSX 10.9.
I will try this on Ubuntu...

**Comment by PauloSeb** [comment]
Working on my Ubuntu 12.04LTS VM... 
You might check modules version with "npm list" to check if something is wrong.
I have :
├── commander@2.1.0
├─┬ midi@0.7.0
│ └── bindings@1.1.1
└── websocket@1.0.8

**Comment by granmoe** [comment]
Thanks for the info. I verified I am indeed running all of the same release levels of the modules. This appears to be a bug within the midi module (same as the issue I linked in my original comment, possibly). I added segfault_handler to the test app, and this is the output from the segmentation fault:

PID 8107 received SIGSEGV for address: 0x11

/home/matt/Programming/NodeProjects/MIDI/midiserver/node_modules/segfault-  handler/build/Release/segfault_handler.node(+0xf1e)[0x7ff4e9e8ff1e]

/lib/x86_64-linux-gnu/libpthread.so.0(+0xfcb0)[0x7ff4ea461cb0]

node(uv_unref+0x1d)[0x95db7d]

/home/matt/Programming/NodeProjects/MIDI/midiserver/node_modules/midi/build/Release/midi.node(_ZN13NodeMidiInput3NewERKN2v89ArgumentsE+0x2a4)[0x7ff4e9c8a2c4]

node[0x5c490d]

[0x9712aa06362]

**Comment by granmoe** [comment]
I'll close this since this isn't a bug with your project. Thanks for the reply, though!

Regards
